---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: centos-6
  driver_config:
    box: bento/centos-6.7
- name: ubuntu-12.04
  driver_config:
    box: bento/ubuntu-12.04
- name: ubuntu-15.04
  driver_config:
    box: bento/ubuntu-15.04
  run_list:
    - recipe[apt]
  attributes:
    jira:
      init_type: systemd
    postgresql:
      # postgresql cookbook doesn't support 15.04 yet.
      version: '9.4'
      enable_pgdg_apt: false

suites:
- name: installer-postgresql
  run_list:
  - recipe[jira]
  attributes:
    jira:
      install_type: installer
      database:
        type: postgresql

- name: standalone-postgresql
  run_list:
  - recipe[java]
  - recipe[jira]
  attributes:
    java:
      install_flavor: oracle
      java_home: /usr/lib/jvm/java-8-oracle
      jdk_version: 8
      oracle:
        accept_oracle_download_terms: true
    jira:
      install_type: standalone
      database:
        type: postgresql
        host: localhost
        port: 5432
