AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
  Exclude:
    - test/**/*
    - vendor/**/*
    - ruby/**/*

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
# Disable %Q() checker due to false positive in crowd_sso.rb
Style/BarePercentLiterals:
  Enabled: false
